name: Automated Ollama Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  ollama_review:
    runs-on: ubuntu-latest
    name: Ollama Code Review Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Ollama Code Review
        uses: ./.github/actions/ollama_review
        with:
          llm-model: 'codellama'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
